# File konfigurasi nginx (/docker/nginx/default.conf) 
server {
    listen 80;
    server_name localhost;

    # PENTING: Path root ini HARUS SAMA dengan WORKDIR 
    # yang ada di dalam Dockerfile PHP-FPM (/var/www/html)
    root /var/www/html;
    
    # Prioritaskan index.php sebelum index.html
    index index.php index.html;

    # Pengaturan agar URL rapi (Pretty URL)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bagian Krusial: Mengirim file .php ke Container PHP
    location ~ \.php$ {
        # CATATAN PENTING UNTUK PROSES BUILD/RUN:
        # "php-service" adalah nama HOSTNAME container PHP.
        # 1. Jika pakai Docker Compose: Ini harus sama dengan nama service di docker-compose.yml
        # 2. Jika pakai Docker Run Manual: Ini harus sama dengan '--name' container PHP Anda.
        #    Contoh: fastcgi_pass nama-container-php-anda:9000;
        fastcgi_pass phpfpm-service:9000;
        
        fastcgi_index index.php;
        
        # SCRIPT_FILENAME memberi tahu PHP file mana yang harus dieksekusi di dalam containernya
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        include fastcgi_params;
    }
}
